---
name: Automation Regression Testing CI
'on':
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: regression-test-suite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21 (Temurin) and enable Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run Regression Tests (Maven wrapper on Windows)
        shell: cmd
        run: >-
          .\mvnw.cmd clean test -Dtest=tests.combined.CombinedSuiteRunner
          -Dmaven.test.failure.ignore=true
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-reports
          path: |
            target/surefire-reports/**  # <-- Standard Maven reports
          retention-days: 30
      - name: Upload screenshots & artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-screenshots
          path: |
            artifacts/**  # <-- Adjust if your artifacts folder is different
          retention-days: 30
      - name: Publish test results to GitHub
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Regression Suite
          path: target/surefire-reports/**/*.xml
          reporter: junit
